# Generated by Django 3.2.8 on 2021-10-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('floor_number', models.IntegerField(default=1)),
                ('city', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=50)),
                ('trade_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shop.tradecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('manufacture_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('shop', models.ManyToManyField(to='shop.Shop')),
            ],
        ),
    ]
