# Generated by Django 3.2.8 on 2021-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradecompany',
            options={'verbose_name_plural': 'trade companies'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='will be aggregated in save', max_length=100),
        ),
    ]
