# Generated by Django 3.2.8 on 2021-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211012_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='not_change_if_dont_want_custom', max_length=100),
        ),
    ]
