# Generated by Django 3.2.8 on 2021-10-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trade_mark',
            field=models.CharField(default='Nestle', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='not_change_if_dont_want_custom', max_length=100),
        ),
    ]
