# Generated by Django 3.2.8 on 2021-10-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211012_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(null=True, to='shop.Shop'),
        ),
    ]
