# Generated by Django 3.2.8 on 2021-10-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Shop'),
        ),
    ]
